Repository VorTECHsa/dynamicio, pull requests merged in 2022-10, with the labels that each got.

#24 refactor: Remove boiler plate code for IO classes
  .pylintrc
  README.md
  demo/src/io.py
  demo/src/runners/staging.py
  demo/src/runners/transform.py
  dynamicio/core.py
  dynamicio/errors.py
  tests/test_core.py
Labels: enhancement, good first issue

#29 feat: Extend has equal validation
  README.md
  docs/config.html
  docs/core.html
  docs/errors.html
  docs/index.html
  docs/mixins.html
  docs/validations.html
  dynamicio/core.py
  dynamicio/validations.py
  tests/conftest.py
  tests/resources/schemas/foo.yaml
  tests/resources/schemas/read_from_s3_csv.yaml
  tests/resources/schemas/write_to_s3_csv.yaml
  tests/test_validations.py
Labels: enhancement

#31 fix: Confirm floats are not returned unless a repl takes place
  dynamicio/config.py
  tests/resources/schemas/bar.yaml
  tests/test_config.py
Labels: bug
