Repository VorTECHsa/dynamicio, pull requests merged in 2023-01, with the labels that each got.

#37 feat: No disk space h5
  dynamicio/mixins/utils.py
  dynamicio/mixins/with_local.py
  dynamicio/mixins/with_s3.py
  tests/conftest.py
  tests/test_mixins/test_s3_mixins.py
Labels: enhancement, echoes/effort: M

#40 refactor: Introduce Pydantic
  .flake8
  .pylintrc
  demo/tests/test_pipeline.py
  dynamicio/__init__.py
  dynamicio/config/__init__.py
  dynamicio/config/io_config.py
  dynamicio/config/pydantic/__init__.py
  dynamicio/config/pydantic/config.py
  dynamicio/config/pydantic/io_resources.py
  dynamicio/config/pydantic/table_schema.py
  dynamicio/core.py
  dynamicio/mixins/__init__.py
  dynamicio/mixins/with_kafka.py
  dynamicio/mixins/with_local.py
  dynamicio/mixins/with_postgres.py
  dynamicio/mixins/with_s3.py
  dynamicio/validations.py
  requirements-dev.txt
  requirements.txt
  tests/conftest.py
  tests/resources/definitions/input.yaml
  tests/test_config.py
  tests/test_core.py
  tests/test_mixins/test_local_mixins.py
  tests/test_mixins/test_postgres_mixins.py
  tests/test_mixins/test_s3_mixins.py
Labels: enhancement, echoes/effort: L

#43 refactor: Introduce Pydantic
  .circleci/config.yml
  .flake8
  .pylintrc
  demo/tests/test_pipeline.py
  dynamicio/__init__.py
  dynamicio/config/__init__.py
  dynamicio/config/io_config.py
  dynamicio/config/pydantic/__init__.py
  dynamicio/config/pydantic/config.py
  dynamicio/config/pydantic/io_resources.py
  dynamicio/config/pydantic/table_schema.py
  dynamicio/core.py
  dynamicio/mixins/__init__.py
  dynamicio/mixins/with_kafka.py
  dynamicio/mixins/with_local.py
  dynamicio/mixins/with_postgres.py
  dynamicio/mixins/with_s3.py
  dynamicio/validations.py
  requirements-dev.txt
  requirements.txt
  tests/conftest.py
  tests/mocking/io.py
  tests/resources/definitions/input.yaml
  tests/test_config.py
  tests/test_core.py
  tests/test_mixins/test_local_mixins.py
  tests/test_mixins/test_postgres_mixins.py
  tests/test_mixins/test_s3_mixins.py
  tests/test_regressions/conftest.py
  tests/test_regressions/resources/missing_v430_validations.yaml
  tests/test_regressions/test_v430.py
Labels: echoes/effort: L
